### ISSUE TITLE
How to polygonize points in roof ?

### ISSUE THREAD

**Issue by derekcbr** [aegis1980/cad_to_shapely#1]
Is it possible to polygonize different points in the roof by this algorithm? As a roof consists of different polygons.

**Comment by aegis1980** [comment]
Hey. Not sure I quite understand, but don't think so. This code just
converts 2D CAD files (dxf,dwg) to Shapely geometry. Shapely a Python
library.
Your problem sounds more a 3d modeling problem? If you send me snapshot
image might be able to point in right direction ;) that sort of thing is
more my day job with coding after hours. Ha.

**Comment by derekcbr** [comment]
Thanks! Please have a look at the roof picture. 

![Uploading roof001.jpg…]()

**Comment by aegis1980** [comment]
your u/l image didnt work...

**Comment by derekcbr** [comment]
Please check again!
![roof001](https://user-images.githubusercontent.com/31892214/110732951-13777800-8260-11eb-889b-3db3b4f3681d.jpg)

**Comment by aegis1980** [comment]
What r you trying to do?
Make a 3d model of roof, ie create sloped surfaces? You'll need some
height/slope info to do that.
Or just define closed 2d  polygons for each facet of roof?
Is that image you sent a screenshot of a dwg/vector file? Or a raster one
(jpeg etc?)

**Comment by derekcbr** [comment]
I am trying to calculate the roofing areas by each polygons based on the slope already know. It is from dwg file.
![roof002](https://user-images.githubusercontent.com/31892214/110740588-458fd680-826e-11eb-8a9e-145c602dde6e.jpg)

**Comment by aegis1980** [comment]
for this specific geometry (ie a one-off) or more broadly?
specific: easyish. use AutoCAD, Rhino, Sketchup ++ whatever (gimme the
file, I can do it). What format for you need for? Alternatively, the
person/architect who created the original file has te 3d info so ask her to
send it.
more broadly (as a bit code): tough, beyond my sphere of interest....but
solvable! Good luck!!

Jon

**Comment by derekcbr** [comment]
Thanks! I was inspired by your project and then I use shapely.ops.polygonize(rooflines) but it only four polygons and others are invalids.geoms. The architect does not have 3D format as it is only in quoting phase.

**Comment by aegis1980** [comment]
Sweet. Glad you've sorted it 😉
Sorry if my messages may've come across a little back-to-basics. Wasn't
100% sure what experience etc u had.
Jon

**Comment by derekcbr** [comment]
Thank you for the help!
