### ISSUE TITLE
Shapely deprecations

### ISSUE THREAD

**Issue by connorferster** [aegis1980/cad_to_shapely#2]
Shapely is deprecating two behaviours that currently exist in cad-to-shapely.
1. Iterating multi-geometries to access constituent geometries (shapely 1.8.0 requests the use of the new `.geoms` attribute for this)
2. Setting custom attributes on geometries (which cad-to-shapely does but does not seem to rely on the `_attribs` information to perform its main task)

I will submit a pull request for the updates.

**Comment by aegis1980** [comment]
hey,
Just adding LINE (and ARC) dxf import, to address the section properties issue i saw come up.
the `test_cad_to-shapely.py` file you added. What test framework does this use? 
Suspect well be a noob question, so humour me. Am a little python rusty. 
jon

**Comment by connorferster** [comment]
Heyo! Very cool! 

It uses pytest. Curious to hear how the addition goes. If you are able to add line and arc that would be soooo boss!

**Comment by aegis1980** [comment]
I've added LINE and ARC to dxf importer (plus ARCs in POLYLINES, which it turns out is a 'thing' too. Urrgh!) on dev branch.
Works with various dxfs I have tried - bound to be one that does not work though.

**Comment by connorferster** [comment]
Amazing.

I am curious to play with it this weekend!

**Comment by robbievanleeuwen** [comment]
Hi @aegis1980, awesome that this is being added. I'll chuck three files into the mix, see attached below. `test1` & `test3` look to be almost there, but some of the rounded corners seem to be a bit off. `test2` won't load for me, I get the following error:

```shell
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    my_dxf.process()
  File "C:\Users\Robbie\Downloads\cad-to-shapely-master\cad_to_shapely\dxf.py", line 139, in process
    self._process_2d_polyline(e)
  File "C:\Users\Robbie\Downloads\cad-to-shapely-master\cad_to_shapely\dxf.py", line 49, in _process_2d_polyline
    pts = utils.arc_points_from_bulge(p1,p2,v1.dxf.bulge,degrees_per_segment)
  File "C:\Users\Robbie\Downloads\cad-to-shapely-master\cad_to_shapely\utils.py", line 122, in arc_points_from_bulge
    k = math.sqrt((radius**2)-(d/2)**2)
ValueError: math domain error
```

This will be great once it's implemented, love your work!

[dxf_test.zip](https://github.com/aegis1980/cad-to-shapely/files/8029894/dxf_test.zip)

**Comment by aegis1980** [comment]
Mmmm. interesting...
...Interesting that you might be in facades now???
haha

Will take a look - think its nearly there with some ironing-out.

**Comment by robbievanleeuwen** [comment]
Haha actually not in engineering at all anymore! These files were emailled to me by someone trying to get the dxf feature on *sectionproperties* to work :)

**Comment by aegis1980** [comment]
good decision leaving engineering.

will try and fix on the sections u attached. I know what the issue is but
need to feel inspiration to fix it!
